#!/bin/bash

echo "GitHub Push 스크립트"
echo "===================="
echo ""
echo "GitHub 사용자명과 Personal Access Token이 필요합니다."
echo ""
echo "Personal Access Token 만들기:"
echo "1. GitHub.com 로그인"
echo "2. Settings → Developer settings → Personal access tokens → Tokens (classic)"
echo "3. Generate new token (classic) 클릭"
echo "4. Note: 아무거나 (예: naver-analyzer)"
echo "5. Expiration: 30 days"
echo "6. Select scopes: 'repo' 체크박스 선택"
echo "7. Generate token 클릭"
echo "8. 생성된 토큰 복사 (한 번만 보여짐!)"
echo ""
echo "준비되면 아래 명령어를 실행하세요:"
echo ""
echo "git push https://YOUR_USERNAME:YOUR_TOKEN@github.com/darkdaddy/naver-shopping-analyzer.git main"
echo ""
echo "YOUR_USERNAME: GitHub 아이디"
echo "YOUR_TOKEN: 방금 만든 Personal Access Token"
echo ""
echo "예시:"
echo "git push https://darkdaddy:ghp_xxxxxxxxxxxx@github.com/darkdaddy/naver-shopping-analyzer.git main"